### ISSUE TITLE
Error after starting with Docker

### ISSUE THREAD

**Issue by RamiAlzayat** [miscord-dev/palog#12]
Hello,

I"m getting this error on my Palworld Linux server 

`ERROR failed to get players error="failed to connect to 127.0.0.1:25575: rcon: dial tcp 127.0.0.1:25575: connect: connection refused"`

I have both `RCONEnabled=True,RCONPort=25575` settings in my `/home/steam/Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini` 

and if i inspect the container i see 
```
            "Env": [
                "RCON_ENDPOINT=127.0.0.1:25575",
                "RCON_PASSWORD=mypassword",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
```
FYI:
- [palog](https://github.com/miscord-dev/palog) is on the same host as the server.
- I'm able to run RCON commands from my Windows machine via [ARRCON](https://github.com/radj307/ARRCON)
- i started the palog with `docker run --name palog -e RCON_ENDPOINT=127.0.0.1:25575 -e RCON_PASSWORD=mypass ghcr.io/miscord-dev/palog:v0.0.5`

Could you please help me out to get this container to work?
Thanks a lot :)

**Comment by RamiAlzayat** [comment]
i just tried the binary install, it is working but i also get an error there
`2024/01/31 15:22:53 ERROR failed to run uconv error="exec: \"uconv\": executable file not found in $PATH"`

**Comment by tsuzu** [comment]
@RamiAlzayat 
When you run palog on Docker, the endpoint isn't localhost because Docker runs containers inside network namespaces.
There are two fixes.

* Run palog with `--net=host`
    * You can connect to the PalWorld server via localhost
* If you also run the PalWorld server on Docker, consider running it and palog via docker-compose
    * On docker-compose, containers can connect to each other via their service names.

> 024/01/31 15:22:53 ERROR failed to run uconv error="exec: \"uconv\": executable file not found in $PATH"

Set the following env to disable the message.
```
export UCONV_LATIN=false
```
This feature is helpful for CJK users to convert characters to alphabetical characters.
but not necessary if all names are represented by only ASCII characters.

**Comment by tsuzu** [comment]
Has the issue been resolved? May I proceed to close this issue?

**Comment by tsuzu** [comment]
Closing this issue.
If you still have the problem, please create a new issue
